Log ALL the things

diff --git a/libexec/ensure/ensure-install b/libexec/ensure/ensure-install
--- a/libexec/ensure/ensure-install
+++ b/libexec/ensure/ensure-install
@@ -1,7 +1,11 @@
-#!/usr/bin/env bash
+#!/bin/sh
+
+set -e
+
+source "$ENSURE_LIB/helpers.sh"
 
 if [ -f "$ENSURE_MANIFEST" ]; then
   source "$ENSURE_MANIFEST";
 else
-  echo "Can't find ensure manifest at \"${ENSURE_MANIFEST}\"" >&2
+  log_error "Can't find ensure manifest at \"${ENSURE_MANIFEST}\""
 fi
